In [35]:
#Import Packages
import pandas as pd
import numpy as np

A **Series** is a one-dimensional array

- Unlike a NumPy array, they have an ***index***

In [36]:
#Create a numpy array
arr = np.random.randn(4) #Creates an array of random values from a std normal distribution
print(type(arr))
print(arr, "/n")

#Creat a pandas series from the numpy array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[ 1.80806369  0.1928356  -0.60908147 -1.00008085] /n
<class 'pandas.core.series.Series'>
0    1.808064
1    0.192836
2   -0.609081
3   -1.000081
dtype: float64

- numpy arrays have an implicit index (they can still be indexed by position)
- pandas series have an explicit index (printed as part of the data structure.  Printing a pandas series also shows the data type)

**Creating a pandas series**
s = pd.Series(data, index=index)
- data can be a list, array, dictionary, single value
- index takes a list (optional, but if included it must be as long as the data)

In [37]:
#From a NumPy array
pd.Series(np.arange(3), index = [2023, 2024, 2025])

2023    0
2024    1
2025    2
dtype: int64

In [38]:
#From a list
#Use the default index
pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: object

In [39]:
#From a dictionary

#Construct the dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}

#Initialize the series
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

Data type is an object becuase it is a combination of strings and numbers

In [40]:
#If we give only a single value, the series is filled with that value
pd.Series(3.0, index = ['A', 'B', 'C'])

A    3.0
B    3.0
C    3.0
dtype: float64

In [41]:
#You can do simple operations on a series

#Define the Series
s = pd.Series([98,73,65], index =['Andrea', 'Beth', 'Carolina'])

#Divide each element by 10
print(s/10, '\n')

#Take the exponential of each element (What is an exponential?)
print(np.exp(s), '\n')

#Unless you save an operation under the same name, the original series is unchanged
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

In [42]:
#Produce a new series of T/F indicating whether each value in the original series satisfies a condition
s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

In [43]:
#We can identify missing numbers

#Make a series with some missing values
s = pd.Series([1, 2, np.nan, 4, np.nan])
print(s)

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

Notice that the data type is still a float-- this is because pandas recognizes NaN as empty values

In [44]:
#Check if there are any empty values or NAs using hasnans
s.hasnans

True

In [45]:
#Use isna to locate them by creating a series of boolean outputs for each value
s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

**Check In 1-2**

In [46]:
#Create a pandas.Series named s with four integer values, two of which are -999. 
# The index of this series should be the letters A through D.

s2 = pd.Series(data = [7, -999, 4, -999], index = ['A', 'B', 'C', 'D'])
s2.mask(s2 == -999)

A    7.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [47]:
#A dataframe is essentailly a dictionary of pandas Series.  Create it like one!

#Innitalize the dictionary with the data for each column
d = {'col_name_1':pd.Series(np.arange(3)),
     'col_name_2':pd.Series([3.1, 3.2, 3.3])
     }

#Create the dataframe
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [48]:
#Change the index using index
df.index = ['a', 'b', 'c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

In [51]:
#Use .rename to change the column names
df.columns = ['C1', 'C2']

In [ ]:
#Use .rename to rename columns
#df.rename(columns = {'col_name_1':'C1',
#              'col_name_2':'C2'})
#df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3